/* Generated by tools/mksplash.py -- do not edit by hand.
 *
 * LA64M68 splash screen, Amiga Denise/OCS and Atari ST compatible:
 * 320x200, 16 colours, every colour on a 3-bit channel step so both machines
 * render the identical shade. The raster itself lives in assets/ next to the
 * executable (program root), see vsplash.c.
 *
 * Copyright (C) 2026 LA64M68 contributors
 * Non-Profit Software under the GNU General Public License v3.0 or later.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
#ifndef LA64M68_VSPLASH_H
#define LA64M68_VSPLASH_H

#include <stdint.h>

#define LA64M68_VSPLASH_WIDTH   320
#define LA64M68_VSPLASH_HEIGHT  200
#define LA64M68_VSPLASH_COLORS  16

/* 0xRGB, 4 bits per channel (Amiga). The Atari ST shows the same shade with
 * 3 bits per channel because every entry sits on a 0x111 step. The values
 * live in assets/splash.pal and are loaded with the raster. */
extern uint16_t la64m68_vsplash_palette[LA64M68_VSPLASH_COLORS];

/* Load assets/ relative to the program root. Returns 0 when the splash is
 * available, -1 when it is not (which is not an error: it only means no
 * splash). */
int          la64m68_vsplash_load(const char *root);
int          la64m68_vsplash_ready(void);
const uint8_t *la64m68_vsplash_chunky(void);

/* Primary surface: VideoCore / vRTG want true colour. */
void la64m68_vsplash_render_rgb24(uint8_t *out, uint32_t stride);
/* 16-bit 1:4:4:4, the Amiga-native style. */
void la64m68_vsplash_render_rgb16(uint16_t *out, uint32_t stride_words);

#endif
